### ISSUE TITLE
How to install on parabola distro?

### ISSUE THREAD

**Issue by ZerdoX-x** [waydroid/docs#37]
due to #11

**Comment by Runa-Chin** [comment]
> And artix linux too

@tiziodcaio For Artix Linux, follow what Arch Linux official do and change it for ```systemctl``` argument with any service manager from what init you had use such as OpenRC with RC or another init service manager you got on Artix.

**Comment by Runa-Chin** [comment]
> due to #11

For Parabola, it's based on Arch Linux. And, I should to follow Arch Linux official guide for this distro and make sure you had use x64 edition for this distro. If you need it for x86, I suggest you to use openSUSE Tumbleweed instead and [follow my guides if you want on openSUSE](https://github.com/waydroid/waydroid/discussions/1463).
