### ISSUE TITLE
How to update Lineage OS major version image release without full re-install?

### ISSUE THREAD

**Issue by BillFleming** [waydroid/docs#42]
Please provide an FAQ/guide page on the proper commands to upgrade from one major release to another (Lineage OS 17.1 to 18, etc).
When I did an upgrade recently on my pinephone it failed to boot, but I don't want to have to re-install everything from scratch, and generate a new GAPPs phone ID, etc from a fresh install.

Is seedvault the recommended way of doing this? https://docs.waydro.id/faq/backup-restore-apps-and-data

Which waydroid folders (if any) need to be deleted before doing the first boot of the new installation?
Is a specific init command sequence required?

I have my pinephone pro setup with a full backup (and still on lineage 17) so I can test this process out over the weekend.

An issue will come up that on many distros the images are updated from the package manager, so possibly waydroid itself needs a way to detect that you changed images from a system upgrade. Probably a separate issue will need to be created for such a feature enhancement...

**Comment by aleasto** [comment]
Upgrading does not require any intervention.
